### ISSUE TITLE
relationship to verifiable claims

### ISSUE THREAD

**Issue by iherman** [json-ld/charter#6]
The current text says:

> Coordination on named graph indexing and support for <a href="https://json-ld.github.io/normalization/spec/">RDF Dataset Normalization</a> and <a href="https://w3c-dvcg.github.io/ld-signatures/">Linked Data Signatures</a>.

That may be a bit misleading: it suggests that this group will take on Normalization and Signatures, which is not the case (should we add this to the "out of scope" section, b.t.w.?). I think the exact nature of the relationship should be a bit more "vague"...

**Comment by msporny** [comment]
Agreed that there is no group at W3C that is currently tackling RDF Dataset Normalization and Linked Data Signatures (not JSON-LD 1.1, not VCWG, etc.). Yes, I think we should add it to the out of scope section... even though we're really kicking that particular can down the road. 

At some point soon I'd like to understand how the Linked Data Community is going to come to grips with Dataset Normalization and Linked Data Signatures because we may start pushing for those WGs at W3C (or IETF).

**Comment by gkellogg** [comment]
I think we should probably leave in something about generally supporting JSON normalization, which is a topic of discussion in the IETF, and leave it vague enough to cooperate with other normalization considerations, which may include RDF Dataset Normalization, without specifically calling it out.
